### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by jairopaiva** [nicolas-repiquet/ArchAssembler#1]
Hello Nicholas, congratulations on your work, it's perfect!  Is Github code the last?  If you have any newer version of it, could you please share it?  If not, ignore the request, thank you very much, this code will help me a lot!

 I don't know if you remember, but a few years ago we exchanged a few emails, and you were very attentive and helpful, I will attach a print below that may remind you, it was an assembler project I was building, but I lost it over time  of years and would like to write it again!

[https://raw.githubusercontent.com/jairopaiva/Jairo-Paiva-Language/master/PAsm%20(Assembler).png]

**Comment by nicolas-repiquet** [comment]
Hi Jairo !
Yes I remember your project ! Glad to see you're back at it.
The github version is the last one indeed : I lost interest and never touched it again.
But I might dust it off if you have any needs.

**Comment by jairopaiva** [comment]
Don't worry buddy, you already helped me a lot, when I have time, I'll be back to the code, and any new features I add, I'll post here on git!
